- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Copy file
      ansible.builtin.copy:
        src: /opt/copyfile.txt
        dest: /opt/
